title: Oblyk Documentation
description:
  Trouvez toute la documentations nécessaires pour comprendre et utiliser Oblyk,
  la plateforme communautaire et open source dédiée à l'escalade outdoor et indoor.
#remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.ico"

url: https://oblyk.github.io/app-user-doc
github_repository: https://github.com/oblyk/app-user-doc

aux_links:
  Oblyk App: https://oblyk.org

plugins:
  - jekyll-default-layout

#plugins:
#  - jekyll-remote-theme
